server:
  port: 7001

spring:
  redis:
    host: 175.27.243.243
    port: 6379
    timeout: 1800000
    database: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.27.243.243:3306/ftblog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: ftblog
    password: ftblog
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8